# Generated by Django 5.1.6 on 2025-03-09 01:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursematerial',
            name='uploadURL',
        ),
        migrations.AddField(
            model_name='coursematerial',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='materials/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.CharField(db_index=True, default=uuid.UUID('d8b03724-c8d4-4cdf-b0e4-c89658f6cbba'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='coursematerial',
            name='id',
            field=models.CharField(db_index=True, default=uuid.UUID('9f46dafb-b434-4541-a386-fd940f800cfd'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='coursetracker',
            name='id',
            field=models.CharField(db_index=True, default=uuid.UUID('bbda76d2-ab55-4ca4-b1ea-878bdd84c931'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='interest',
            name='id',
            field=models.CharField(db_index=True, default=uuid.UUID('1518a93e-b852-4a28-818e-b4e060798dd2'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.CharField(db_index=True, default=uuid.UUID('20d1669a-4eeb-4221-879d-f4de23d47da2'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='status',
            name='id',
            field=models.CharField(db_index=True, default=uuid.UUID('a78601ef-4835-4adf-af7d-4fedf03cdfa6'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='studentfeedback',
            name='id',
            field=models.CharField(db_index=True, default=uuid.UUID('4673cd5f-05f9-4f13-887b-08360647d53c'), max_length=100, primary_key=True, serialize=False),
        ),
    ]
