# Generated by Django 5.1.6 on 2025-03-09 11:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_coursematerial_uploadurl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.CharField(db_index=True, default=uuid.UUID('364def35-c2a1-4583-868d-81b8a9fb095d'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='coursematerial',
            name='id',
            field=models.CharField(db_index=True, default=uuid.UUID('e477a254-a422-49e1-86e6-fdeb5230300d'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='coursetracker',
            name='id',
            field=models.CharField(db_index=True, default=uuid.UUID('f86cb528-537c-403e-9aa7-fbf079c8b010'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='interest',
            name='id',
            field=models.CharField(db_index=True, default=uuid.UUID('01b0b02d-25a8-425d-8e65-e33ed835a0c7'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='status',
            name='id',
            field=models.CharField(db_index=True, default=uuid.UUID('94aefdb5-25df-416a-a207-4e95bcf97782'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='studentfeedback',
            name='id',
            field=models.CharField(db_index=True, default=uuid.UUID('52a67544-b465-40ae-97d9-db7d4641ea90'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
